[workspace]
resolver = "2"
members = ["concept", "guppies", "salvage", "run-wasm", "examples/life", "examples/layout"]
default-members = ["examples/layout"]

[profile.release]
lto = true
opt-level = 's'
