[workspace]
resolver = "2"
members = [
  "experiment",
  "guppies",
  "salvage",
  "run-wasm",
  "examples/life",
  "examples/layout",
  "examples/list",
]

[profile.release]
lto = true
opt-level = 's'
