[workspace]
resolver = "2"
members = [
  "concept",
  "guppies",
  "salvage",
  "run-wasm",
  "examples/life",
  "examples/layout",
  "examples/list",
]
default-members = ["examples/list"]

[profile.release]
lto = true
opt-level = 's'
