[package]
name = "usvg_layout"
version = "0.1.0"
edition = "2021"

[dependencies]
usvg = { git = "https://github.com/Cactice/resvg" }
bytemuck = "1.2.0"
glam = { version = "0.20.2", features = ["bytemuck"] }
