[package]
name = "usvg_layout"
version = "0.1.0"
edition = "2021"

[dependencies]
usvg = { git = "https://github.com/Cactice/resvg" }
bytemuck = "1.2.0"
glam = "0.20.2"

[patch.crates-io]
usvg = { git = "https://github.com/Cactice/resvg" }
