[package]
name = "layout"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "layout"
path = "src/main.rs"

[dependencies]
mobile-entry-point = "0.1.0"
bytemuck = "1.12.1"
guppies= { path = "../../guppies" }
salvage = { path = "../../salvage" }
concept = { path = "../../concept" }
