[package]
name = "salvage"
version = "0.1.0"
edition = "2021"

[dependencies]
usvg = { git = "https://github.com/Cactice/resvg" }
guppies = { path = "../guppies" }
lyon = "1.0.0"
roxmltree = "0.14.1"
xmlwriter = "0.1.0"
