[package]
name = "salvage"
version = "0.1.0"
edition = "2021"

[dependencies]
usvg = { git = "https://github.com/Cactice/resvg" }
guppies = { path = "../guppies" }
bytemuck = "1.2.0"
lyon = "0.17.10"
roxmltree = "0.14.1"
xmlwriter = "0.1.0"
